### ISSUE TITLE
Maintenance mode doesn't work

### ISSUE THREAD

**Issue by guillegiu** [opensupports/opensupports#125]
For some reason the front-end doesn't change to maintenance mode when you turned on the button . It's a front-end issue because the API does the changes that it has to do in database.

**Comment by mredigonda** [comment]
Yes, I was able to recreate this bug in my environment.

It seems that the button isn't even changing (it always shows "on"). The ToggleButton in system preferences is lacking a "value" attribute. I'll take a look into this.

Thanks for reporting.

**Comment by mredigonda** [comment]
I did some research and I don't think this is a frontend issue.

The reasons to believe this are that, at least on my local environment:

* Data object passed to `/system/edit-settings` seem to be correct
* Databases are not being updated when calling the `edit-settings` controller from backend.
* After some debugging, I know that the code inside [this if statement](https://github.com/opensupports/opensupports/blob/master/server/controllers/system/edit-settings.php#L56) is being executed when `$setting = 'maintenance-mode'` (of course, even if `maintenance-mode` is different from what it was before).

That's all the info I could find.

**Comment by mredigonda** [comment]
To update this: it is actually both a frontend and a backend problem.

Backend part is already solved in a pull request from @ivandiazwm.

**Comment by LeonBeilis** [comment]
Hey, I just checked it's still not working. I'm able to login with customer user even if its on Maintenance mode enabled
